services:
  medias-api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - media-data:/media
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=mediadb
      - FS_BASE_URL="${FS_BASE_URL}"
    depends_on:
      - medias-mysql
      - medias-filesystem
    networks:
      - proxy-network
      - medias-db

  medias-mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mediadb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - medias-db

  medias-filesystem:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - media-data:/usr/share/nginx/html/media
    networks:
      - proxy-network


volumes:
  media-data:
  mysql-data:



networks:
  medias-db:
  proxy-network:
    external: true